/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package demo.kstreams;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StockKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9029956807103495734L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockKey\",\"namespace\":\"demo.kstreams\",\"fields\":[{\"name\":\"Symbol\",\"type\":\"string\"}],\"connect.name\":\"StockKey\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockKey> ENCODER =
      new BinaryMessageEncoder<StockKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockKey> DECODER =
      new BinaryMessageDecoder<StockKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<StockKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<StockKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StockKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this StockKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a StockKey from a ByteBuffer. */
  public static StockKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Symbol;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockKey() {}

  /**
   * All-args constructor.
   * @param Symbol The new value for Symbol
   */
  public StockKey(java.lang.CharSequence Symbol) {
    this.Symbol = Symbol;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Symbol;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Symbol = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Symbol' field.
   * @return The value of the 'Symbol' field.
   */
  public java.lang.CharSequence getSymbol() {
    return Symbol;
  }

  /**
   * Sets the value of the 'Symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.CharSequence value) {
    this.Symbol = value;
  }

  /**
   * Creates a new StockKey RecordBuilder.
   * @return A new StockKey RecordBuilder
   */
  public static StockKey.Builder newBuilder() {
    return new StockKey.Builder();
  }

  /**
   * Creates a new StockKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockKey RecordBuilder
   */
  public static StockKey.Builder newBuilder(StockKey.Builder other) {
    return new StockKey.Builder(other);
  }

  /**
   * Creates a new StockKey RecordBuilder by copying an existing StockKey instance.
   * @param other The existing instance to copy.
   * @return A new StockKey RecordBuilder
   */
  public static StockKey.Builder newBuilder(StockKey other) {
    return new StockKey.Builder(other);
  }

  /**
   * RecordBuilder for StockKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockKey>
    implements org.apache.avro.data.RecordBuilder<StockKey> {

    private java.lang.CharSequence Symbol;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(StockKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Symbol)) {
        this.Symbol = data().deepCopy(fields()[0].schema(), other.Symbol);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing StockKey instance
     * @param other The existing instance to copy.
     */
    private Builder(StockKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Symbol)) {
        this.Symbol = data().deepCopy(fields()[0].schema(), other.Symbol);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'Symbol' field.
      * @return The value.
      */
    public java.lang.CharSequence getSymbol() {
      return Symbol;
    }

    /**
      * Sets the value of the 'Symbol' field.
      * @param value The value of 'Symbol'.
      * @return This builder.
      */
    public StockKey.Builder setSymbol(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Symbol' field has been set.
      * @return True if the 'Symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Symbol' field.
      * @return This builder.
      */
    public StockKey.Builder clearSymbol() {
      Symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockKey build() {
      try {
        StockKey record = new StockKey();
        record.Symbol = fieldSetFlags()[0] ? this.Symbol : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockKey>
    READER$ = (org.apache.avro.io.DatumReader<StockKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
