spring.cloud.stream.bindings.input.group: so8400replay
spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kstream.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kstream:
  binder.configuration:
    key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    schema.registry.url: http://172.18.0.1:8081
spring.cloud.stream.bindings:
  output:
    destination: stocks.avg
    content-type: application/*+avro
    producer:
      keySerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
      valueSerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
      headerMode: raw
      useNativeEncoding: true
  input:
    destination: stocks.parsed
    content-type: application/*+avro
    consumer:
      headerMode: raw
      startOffset: earliest
spring.cloud.stream.kstream.binder:
  brokers: 172.18.0.1
  zkNodes: 172.18.0.1
spring.cloud.stream.schemaRegistryClient:
  endpoint: 172.18.0.1:8081
  schema.registry.url: http://172.18.0.1:8081